[project]
name = "jupyter-openai-streamlit-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "openai>=1.61.1",
    "streamlit>=1.42.0",
]
